#!/bin/bash

# Get the Real Username
RUID=$(who | awk 'FNR == 1 {print $1}')
# Translate Real Username to Real User ID
RUSER_UID=$(id -u ${RUID})

if [[ -f "/etc/skel/.config/albert/core.db" ]]
    then
        echo "Old File : Delete core.db"
        rm -rf /etc/skel/.config/albert/core.db
fi

if [[ ! -d "/home/$RUID/.config/albert" ]]
then
    echo "Copy settings"
    cp -r /etc/skel/.config/albert /home/$RUID/.config/ || true
    chown -R $RUID:$RUID /home/$RUID/.config/albert || true
else
    echo "Migrate previous settings"
    rm -rf /home/$RUID/.config/albert
    rm -rf /home/$RUID/.cache/albert
    cp -rv /etc/skel/.config/albert /home/$RUID/.config/ || true
    chown -R $RUID:$RUID /home/$RUID/.config/albert || true    
fi