#!/bin/bash

# Get the Real Username
RUID=$(who | awk 'FNR == 1 {print $1}')
# Translate Real Username to Real User ID
RUSER_UID=$(id -u ${RUID})

if [[ ! -d "/home/$RUID/.config/albert" ]]
then
    cp -r /etc/skel/.config/albert /home/$RUID/.config/ || true
    chown -R $RUID:$RUID /home/$RUID/.config/albert || true
fi